name: mysql-stack-for-ecommerce
version: '4'

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-8-0-3
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql